// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tienda.Servicios.Api.CarritoCompra.Persistence;

#nullable disable

namespace Tienda.Servicios.Api.CarritoCompra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220321230332_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tienda.Servicios.Api.CarritoCompra.Models.CarritoSesionDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarritoSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductoSeleccionado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarritoSessionId");

                    b.ToTable("CarritoSesionDetalles");
                });

            modelBuilder.Entity("Tienda.Servicios.Api.CarritoCompra.Models.CarritoSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CarritoSessions");
                });

            modelBuilder.Entity("Tienda.Servicios.Api.CarritoCompra.Models.CarritoSesionDetalle", b =>
                {
                    b.HasOne("Tienda.Servicios.Api.CarritoCompra.Models.CarritoSession", "CarritoSession")
                        .WithMany("CarritoSesionDetalles")
                        .HasForeignKey("CarritoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarritoSession");
                });

            modelBuilder.Entity("Tienda.Servicios.Api.CarritoCompra.Models.CarritoSession", b =>
                {
                    b.Navigation("CarritoSesionDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
